name: Build and push frontend image

on:
  push:
    branches : main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build frontend
        run: |
          docker build -t ghcr.io/yasinbb00/guestbook-frontend:${{ github.sha }} frontend
          docker push ghcr.io/yasinbb00/guestbook-frontend:${{ github.sha }}